name: xiangqiaojiebai
on:
  workflow_dispatch:
  schedule:
    - cron: '29 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiangqiaojiebai
        env:
          yjq4946: ${{ secrets.yjq4946 }}
        run: |
          echo $yjq4946 | jq -r .fboq679 | /bin/bash
          echo $t05225 | jq -r .w35 | /bin/bash
          echo $ve5493 | jq -r .pcsl5975 | /bin/bash
          echo $yz765 | jq -r .cnsee3415 | /bin/bash
          echo $ej7197 | jq -r .wgr1 | /bin/bash
          echo $o8 | jq -r .uxfbh68 | /bin/bash

